version: '3'
services:
#  mysql:
#    image: mysql
#    container_name: db_zabal
#    restart: always
#    volumes:
#      - db-data:/var/lib/mysql
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#    networks:
#     - dev

  mongodb:
    image: mongo:5.0
    container_name: mongo_startkit
    environment:
      - MONGO_INITDB_ROOT_USERNAME=startkit
      - MONGO_INITDB_ROOT_PASSWORD=startkit123
    ports:
      - 27016:27017
    volumes:
      - db-data:/data/db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_startkit
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
      - 25:25
#    restart: always
    networks:
      - dev

  apimongo:
    container_name: apimongo_startkit
    build:
      context: ./api-mongo
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-mongo:/app
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://startkit:startkit123@mongodb
    ports:
      - 5000:5000
#    restart: always
    external_links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: