FROM node:16.13.1

WORKDIR /app

COPY package.json ./

COPY tsconfig.json ./

COPY tsoa.json ./

COPY server ./server

RUN ls -a

RUN npm install && npm install --only=dev

RUN npm install -g tsoa ts-node-dev

EXPOSE 5000

CMD ["npm","run","dev"]