FROM node:current-alpine3.15

WORKDIR /app

COPY package.json ./

COPY tsconfig.json ./

COPY tsoa.json ./

COPY server ./server

RUN npm install --quiet && npm install -g tsoa ts-node-dev --quiet

EXPOSE 5000

CMD ["npm","run","dev"]