version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: ../node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - kits-starter

networks:
  kits-starter: